name: Bygg lunch-sida

on:
  workflow_dispatch:
  schedule:
    - cron: "30 4 * * 1-5"

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - run: python build.py
      - name: Commit & push om ändringar (inkl. nya filer)
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add -A
          if git diff --cached --quiet; then
            echo "Inga nya ändringar att committa."
          else
            git commit -m "Uppdatera lunch-sida: $(date -u +"%Y-%m-%d %H:%M UTC")"
            git push
          fi
